import style from "./AboutApp.module.css";

const AboutApp = () => {
  return (
    <div>
      <div className={style.about}>
        <div className={style.aboutapp}>
          <div>
            <h2>MyMovieShow - About:</h2>
            <br />
            <p>
              The company is currently India’s largest entertainment ticketing
              platform. MyMovieShow started out in 1999 as a software re-seller
              for movie theaters and converted into a platform catering to
              cloud-based ticket booking of events, movies, sports, and plays.
              MyMovieShow was known by the name of its parent company, Bigtree
              Entertainment Pvt. Ltd., at the time of its inception. <br />{" "}
              <br />
              It operates in 5+ countries with more than 30+ million customers.
              In sixteen years, MyMovieShow has been through a roller-coaster
              ride, seeing all kinds of crests and troughs. From INR 25,000 in
              initial capital to INR 391 crores in revenue in FY2018, from the
              'Dot Com' crash in the early 2000s to the global financial crisis
              of 2008, the company has a story at par with the David v/s Goliath
              legend. It managed to sail through tough times and emerged as a
              winner in the end.
            </p>{" "}
            <br /> <br />
          </div>
          <div>
            <h2>MyMovieShow - Industry Details:</h2> <br />
            <p>
              According to a RedSeer report, the online ticketing market in
              India has recorded a quarterly revenue of $28 million. <br />{" "}
              <br />
              Moreover, RedSeer's 'online ticket market updates' report states
              that 50% of the industry revenue has been coming from movies with
              events being the next major contributor. Sporting events,
              concerts, and other live entertainment shows were the significant
              money-making components of the almost $330 million revenue
              generated by the online ticketing industry in 2017 With the big
              guns relentlessly acquiring smaller competitors in this domain, a
              CAGR of 20% is expected in the online ticketing industry by 2020
              according to Wikipedia. Within a decade of its inception,
              MyMovieShow has achieved 40% CAGR in revenues. The company holds
              around 90% market share in the online ticket booking industry.
            </p>
          </div>
          <br /> <br />
          <div>
            <h2>MyMovieShow - Startup Story</h2>
            The alcohol did it for him! After his master's degree, Ashish was
            working for J.W. Thompson, an advertising agency. He was on a
            backpacking trip in South Africa. On one such day, he was sitting
            under a tree listening to the promotion of rugby tickets on radio
            (Newton reincarnated?). An idea sparked in Ashish's mind. Ashish
            came back to India and immediately resigned from his job to focus on
            his idea. He thought of Bigtree Entertainment Pvt. Ltd. as a means
            to transform the niche of ticket booking. However, starting was far
            from easy. When Ashish told his parents about his business idea,
            they weren't happy. Uncertainty and concern hit them like any other
            parents mindful of their child's career but he was able to convince
            them. At the age of 24, he launched his first ever internet venture
            with its head office being his bedroom. Soon after, his friend
            Parikshit Dar joined him to lead the technological aspects and
            another co-founder, Rajesh Balpande, took over the responsibility of
            managing Bigtree's finances. The trio, fondly known as the three
            musketeers, started Bigtree Entertainment Pvt. Ltd. (the parent
            company of BookMyShow) in the process. And that's how MyMovieShow
            started. <br /> <br /> <br />
            <h2>MyMovieShow - Name And Logo</h2>
            MyMovieShow was initially branded as ‘Go For Ticketing’. In 2002,
            the company was renamed ‘India Ticketing’ before ending up with the
            current name. In 2007, the company, then known as India Ticketing,
            organized a contest for its employees where they were to suggest a
            name for the company with the winner receiving an iPod touch. The
            name MyMovieShow was suggested by an engineering intern. And that's
            how the venture found a name that clicked with its mission and
            vision.
          </div>
        </div>
      </div>
      <div className={style.right}>
        <h3>© 2023 MyMovieShow. All Rights Reserved.</h3>
      </div>
    </div>
  );
};
export default AboutApp;
